#+title: Readme

* Motivation
I'm a Doom emacs user, and that's what I'll still be using in my day to day.
This config will try to emulate that experience as much as I can since I don't want to have to context switch between different keybindings and stuff. Also tries to keep terminal emacs in mind, so no C-S chords. A lot of this is basically trying to turn viper into a lightweight evil to be honest.

This is mainly a learning exercise for myself to explore more of vanilla emacs, and also if I ever break my own config then this will be nice to have. With emacs 29, the --init-directory option makes this even easier!

It's also nice to have this on my crappy, but very portable, laptop whenever I want to write some code on the go instead of trying to run Doom on it.

The goal of this is to try and not use any external package, and to try and keep the config simple and light weight. I don't want to re-create doom nor do I want this to become another "distribution". Though I might give myself the option of using some external packages.

So I'm limiting myself to a single file, try and have no more than 1000 lines of code, without doing some weird nasty/complicated code (read: everything on one line lol) just to get within that arbitrary limit.

* Contributions
This is mainly just going to be my own personal config that I'll update from time to time but I recognize that maybe there are others that might be interested in something like this or it's my hubris talking (I'm the best!).

I have a pretty crappy laptop that I like to bring around, and while it /can/ run Doom, something lighter weight like this would help a lot.

Feel free to leave issues but no guarantee I'll ever get to them.
